### PR TITLE
Added UI with tabs

### PR DESCRIPTION
**Pull request by abizukojc**
Documents are presented in a tabbed view.

### CODE REVIEW

**Review by RoughTomato — APPROVED** [review]
Seems fine enough, good work

**Review by RoughTomato — CHANGES_REQUESTED** [review]
merge conflict

**Comment by abizukojc** [comment]
Merge conflicts fixed

**Review by RoughTomato — APPROVED** [review]

**Review by orchowski — COMMENTED** [review]
OK

**Pull request merged**
