### PR TITLE
UML_UZ-37-Karol Dominiak

### PR DESCRIPTION
**Pull request by Gatoke**
Fix of a right-button-click in the Workspace.

### CODE REVIEW

**Review by abizukojc — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Review by orchowski — CHANGES_REQUESTED** [review]
resolve conflicts

**Review by NdV66 — CHANGES_REQUESTED** [review]
ENG and conflicts

**Review by abizukojc — APPROVED** [review]

**Review by orchowski — APPROVED** [review]

**Review by bartoszsledz — APPROVED** [review]
everything works fine in actual master. Approved

**Review by NdV66 — APPROVED** [review]

**Pull request merged**
